import { Lato } from "next/font/google";
import cn from "classnames";
import "./globals.css";

const lato = Lato({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-black">
      <body>
        <main
          className={cn(
            lato.className,
            " w-screen  text-gray-400  overflow-x-hidden"
          )}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
