/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: seenoise (https://sketchfab.com/seenoise)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/office-props-pack-260ff7a37a674505903708a0dc513e7e
title: Office Props Pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

export default function Office(props: GroupProps) {
  const { nodes } = useGLTF('/office/office.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI * 1.2]} position={[1, -3, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={nodes.Object_2.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={nodes.Object_3.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/office/office.gltf')
